export enum DokkuErrorStatus {
  LETSENCRYPT_MANY_REGISTRATION = 'LETSENCRYPT_MANY_REGISTRATION',
  NOT_EXISTS = 'NOT_EXISTS',
  ALREADY_TAKEN = 'ALREADY_TAKEN',
  NOT_YET_DEPLOYED = 'NOT_YET_DEPLOYED',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}
